/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// publish/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CulebraSpellCorrectPlugin
});
module.exports = __toCommonJS(main_exports);

// publish/preview-gateway.ts
var import_obsidian3 = require("obsidian");

// publish/billing-checkout.ts
var import_obsidian = require("obsidian");
var running = /* @__PURE__ */ new WeakMap();
var timers = /* @__PURE__ */ new WeakMap();
async function send(host, path, method, body, key) {
  const request = () => (0, import_obsidian.requestUrl)({
    url: `https://app.tutivsoft.com/api/v1/billing/${path}`,
    method,
    throw: false,
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${host.state.billingAccessToken}`, ...key ? { "Idempotency-Key": key } : {} },
    ...body ? { body: JSON.stringify(body) } : {}
  });
  let response = await request();
  if (response.status === 401 && await host.refreshSession()) response = await request();
  return response;
}
function resumeAccountCheckout(host) {
  var _a;
  if (!host.state.pendingAccountCheckout || !host.state.billingAccountLinked || host.state.pendingAccountCheckout.email !== host.state.billingEmail || timers.has(host.state)) return;
  const timer = setTimeout(() => {
    timers.delete(host.state);
    if (running.has(host.state)) {
      resumeAccountCheckout(host);
      return;
    }
    const operation = recover(host);
    running.set(host.state, operation);
    void operation.catch(() => void 0).finally(() => {
      running.delete(host.state);
      resumeAccountCheckout(host);
    });
  }, 15e3);
  timers.set(host.state, timer);
  (_a = timer.unref) == null ? void 0 : _a.call(timer);
}
async function recover(host) {
  var _a, _b, _c;
  const pending = host.state.pendingAccountCheckout;
  if (!pending || !host.state.billingAccountLinked || pending.email !== host.state.billingEmail) return;
  if (!pending.checkoutId) {
    const response2 = await send(host, "checkout", "POST", { app_id: host.appId, installation_id: host.installationId, plan_code: pending.plan, quantity: 1 }, pending.key);
    if (host.state.pendingAccountCheckout !== pending || pending.email !== host.state.billingEmail) return;
    if (response2.status < 200 || response2.status >= 300 || !((_b = (_a = response2.json) == null ? void 0 : _a.data) == null ? void 0 : _b.checkout_id)) return;
    pending.checkoutId = String(response2.json.data.checkout_id);
    await host.persist();
  }
  const response = await send(host, `checkouts/${encodeURIComponent(pending.checkoutId)}`, "GET");
  if (host.state.pendingAccountCheckout !== pending || pending.email !== host.state.billingEmail) return;
  if (response.status < 200 || response.status >= 300) return;
  const data = (_c = response.json) == null ? void 0 : _c.data;
  if ((data == null ? void 0 : data.settled) || ["completed", "fulfilled", "failed", "canceled", "cancelled", "expired"].includes(data == null ? void 0 : data.status)) {
    await host.syncBalance();
    if (host.state.pendingAccountCheckout !== pending || pending.email !== host.state.billingEmail) return;
    host.state.pendingAccountCheckout = null;
    await host.persist();
  }
}

// publish/constance-account.ts
var import_obsidian2 = require("obsidian");
var CONSTANCE_ACCOUNT_BASE_URL = "https://app.tutivsoft.com";
function errorDetail(response, fallback) {
  var _a, _b;
  const detail = (_a = response.json) == null ? void 0 : _a.detail;
  if ((detail == null ? void 0 : detail.code) === "invalid_credentials") return "Incorrect password. Use Forgot password? to reset it.";
  if ((detail == null ? void 0 : detail.code) === "email_verification_required") return "Email not verified. Click the link in your email, then Connect again.";
  return String((detail == null ? void 0 : detail.message) || (typeof detail === "string" ? detail : "") || ((_b = response.json) == null ? void 0 : _b.message) || fallback);
}
async function authenticate(mode, email, password, installationId) {
  var _a, _b, _c, _d;
  const body = mode !== "login" ? { email, password, external_customer_id: installationId } : { email, password };
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/${mode}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Billing ${mode} failed (HTTP ${response.status})`));
  }
  if (((_a = response.json) == null ? void 0 : _a.verification_required) === true) return { verificationRequired: true };
  const token = String(((_b = response.json) == null ? void 0 : _b.access_token) || "");
  const refreshToken = String(((_c = response.json) == null ? void 0 : _c.refresh_token) || "");
  if (token && refreshToken) return { accessToken: token, refreshToken, expiresIn: Number((_d = response.json) == null ? void 0 : _d.expires_in) || 900 };
  throw new Error("Constance did not return an account token.");
}
async function linkInstallation(adapter, token) {
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/installations/link`,
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      app_id: adapter.appId,
      installation_id: adapter.installationId,
      legacy_external_customer_id: adapter.installationId,
      platform: "obsidian",
      app_version: adapter.appVersion || void 0
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Installation link failed (HTTP ${response.status})`));
  }
}
async function signInBillingAccount(adapter, password, mode) {
  const email = adapter.state.billingEmail.trim().toLowerCase();
  const journalState = adapter.state;
  const owner = String(journalState.pendingBillingOwnerEmail || "").toLowerCase();
  if (owner && owner !== email) throw new Error(`An unfinished billing request belongs to ${owner}. Connect that account to recover it first.`);
  if (!email || !email.includes("@")) throw new Error("Enter a valid billing email.");
  if (Array.from(password).length < 8 || Array.from(password).length > 128) throw new Error("Password must be between 8 and 128 characters.");
  if (!adapter.installationId) throw new Error("The plugin installation ID is not ready.");
  const result = await authenticate(mode, email, password, adapter.installationId);
  if (!result.accessToken) {
    clearBillingSession(adapter.state);
    adapter.state.billingEmail = email;
    adapter.state.billingAccountLinked = false;
    adapter.state.billingRegistrationPending = true;
    await adapter.persist();
    throw new Error("Registered but not logged in. Check your email, click the confirmation link, then sign in here.");
  }
  await completeBillingSignIn(adapter, email, result);
}
async function completeBillingSignIn(adapter, email, session) {
  if (!session.accessToken || !session.refreshToken) throw new Error("Constance did not return a complete account session.");
  await linkInstallation(adapter, session.accessToken);
  adapter.state.billingEmail = email;
  adapter.state.billingAccessToken = session.accessToken;
  adapter.state.billingRefreshToken = session.refreshToken;
  adapter.state.billingAccessExpiresAt = Date.now() + (session.expiresIn || 900) * 1e3;
  adapter.state.billingAccountLinked = true;
  adapter.state.billingRegistrationPending = false;
  await adapter.persist();
  await adapter.syncBalance();
}
function clearBillingSession(state) {
  state.billingAccessToken = "";
  state.billingRefreshToken = "";
  state.billingAccessExpiresAt = 0;
  state.billingAccountLinked = false;
}
var refreshInFlight = null;
async function refreshBillingSession(state, persist) {
  if (!state.billingRefreshToken) return false;
  if (refreshInFlight) return refreshInFlight;
  const originalToken = state.billingRefreshToken;
  refreshInFlight = (async () => {
    var _a, _b, _c;
    let response;
    try {
      response = await (0, import_obsidian2.requestUrl)({ url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/refresh`, method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refresh_token: originalToken }), throw: false });
    } catch (e) {
      return false;
    }
    if (state.billingRefreshToken !== originalToken) return false;
    if (response.status === 401 || response.status === 403) {
      clearBillingSession(state);
      await persist();
      return false;
    }
    if (response.status < 200 || response.status >= 300) return false;
    const access = String(((_a = response.json) == null ? void 0 : _a.access_token) || "");
    const refresh = String(((_b = response.json) == null ? void 0 : _b.refresh_token) || "");
    if (!access || !refresh) {
      clearBillingSession(state);
      await persist();
      return false;
    }
    state.billingAccessToken = access;
    state.billingRefreshToken = refresh;
    state.billingAccessExpiresAt = Date.now() + (Number((_c = response.json) == null ? void 0 : _c.expires_in) || 900) * 1e3;
    await persist();
    return true;
  })();
  try {
    return await refreshInFlight;
  } finally {
    refreshInFlight = null;
  }
}
async function requestAuthenticatedBilling(state, persist, options) {
  if (state.billingRefreshToken && (!state.billingAccessToken || Date.now() >= state.billingAccessExpiresAt - 6e4)) {
    if (!await refreshBillingSession(state, persist) && state.billingRefreshToken) return { status: 503 };
  }
  const send3 = () => (0, import_obsidian2.requestUrl)({ ...options, headers: { ...options.headers || {}, Authorization: `Bearer ${state.billingAccessToken}` }, throw: false });
  if (!state.billingAccessToken) return { status: 401 };
  let response = await send3();
  if (response.status === 401 && state.billingRefreshToken) {
    if (await refreshBillingSession(state, persist)) response = await send3();
    else if (state.billingRefreshToken) return { status: 503 };
  }
  return response;
}
async function pollAuthenticatedCheckout(adapter, checkoutId) {
  var _a, _b;
  if (!adapter.state.billingAccessToken || !adapter.state.billingAccountLinked) return false;
  const response = await requestAuthenticatedBilling(adapter.state, adapter.persist, {
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/checkouts/${encodeURIComponent(checkoutId)}`,
    method: "GET",
    throw: false
  });
  return response.status >= 200 && response.status < 300 && ((_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.settled) === true;
}
async function claimAccountFreeUsage(state, persist, appId, installationId, eventId, amount) {
  var _a, _b;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    const response = await requestAuthenticatedBilling(state, persist, {
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/free-usage/claim`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId, amount }),
      throw: false
    });
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    const remaining = Math.max(0, Number((_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.remaining) || 0);
    new import_obsidian2.Notice(`Credit balance before this task: ${(remaining + amount).toLocaleString()} free credits.`);
    new import_obsidian2.Notice(`Task used ${amount.toLocaleString()} credits. Balance remaining: ${remaining.toLocaleString()} free credits.`);
    return { kind: "ok", remaining };
  } catch (error) {
    console.error("Constance account free-usage claim failed", error);
    return { kind: "error" };
  }
}
async function spendAccountCredits(state, persist, appId, installationId, eventId, amount) {
  var _a, _b, _c;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    const response = await requestAuthenticatedBilling(state, persist, {
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/credits/spend`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId, amount }),
      throw: false
    });
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    const balance = Number((_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance);
    if (!Number.isFinite(balance)) return { kind: "error" };
    const remaining = Math.max(0, balance);
    new import_obsidian2.Notice(`Credit balance before this task: ${(remaining + amount).toLocaleString()} purchased credits.`);
    new import_obsidian2.Notice(`Task used ${amount.toLocaleString()} credits. Balance remaining: ${remaining.toLocaleString()} purchased credits.`);
    return { kind: "ok", balance: remaining };
  } catch (error) {
    console.error("Constance authenticated credit spend failed", error);
    return { kind: "error" };
  }
}
function addBillingAccountSettings(containerEl, adapter) {
  resumeAccountCheckout({ ...adapter, refreshSession: () => refreshBillingSession(adapter.state, adapter.persist) });
  let password = "";
  const section = containerEl.createDiv({ cls: "constance-account-billing-section" });
  section.createEl("h3", { text: "Account and billing" });
  const state = adapter.state;
  const numericBalances = Object.entries(state).filter(([key, value]) => /(?:credit|balance|remaining)/i.test(key) && typeof value === "number").map(([key, value]) => `${key.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase()}: ${Number(value).toLocaleString()}`);
  const accountStatus = adapter.state.billingAccountLinked ? `Signed in as ${adapter.state.billingEmail || "your account"}` : state.billingRegistrationPending ? `Registered as ${adapter.state.billingEmail} but not signed in. Check your email, click the confirmation link, then sign in here.` : "Not signed in.";
  section.createEl("p", {
    cls: "constance-account-status",
    text: numericBalances.length ? `${accountStatus} Balance \u2014 ${numericBalances.join("; ")}` : accountStatus
  });
  if (!adapter.state.billingAccountLinked) {
    new import_obsidian2.Setting(section).setName("Email").setDesc("Used to register, sign in, restore purchases, and open checkout.").addText((text) => text.setPlaceholder("you@example.com").setValue(adapter.state.billingEmail).setDisabled(adapter.state.billingAccountLinked).onChange(async (value) => {
      const journalState = adapter.state;
      const hasPending = Object.entries(journalState).some(([key, value2]) => /^pending/i.test(key) && key !== "pendingBillingOwnerEmail" && !!value2 && (Array.isArray(value2) ? value2.length > 0 : typeof value2 === "object" ? Object.keys(value2).length > 0 : true));
      if (hasPending && !journalState.pendingBillingOwnerEmail) journalState.pendingBillingOwnerEmail = adapter.state.billingEmail;
      if (!hasPending) journalState.pendingBillingOwnerEmail = void 0;
      adapter.state.billingEmail = value.trim();
      await adapter.persist();
    }));
    new import_obsidian2.Setting(section).setName("Password").setDesc("Used only for this request. The plugin never saves your password.").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.maxLength = 256;
      text.setPlaceholder("8 to 128 characters").onChange((value) => {
        password = value;
      });
    });
  }
  new import_obsidian2.Setting(section).setName("Account").setDesc(accountStatus).addButton((button) => {
    if (adapter.state.billingAccountLinked) {
      button.buttonEl.remove();
      return;
    }
    button.setButtonText("Connect").setDisabled(adapter.state.billingAccountLinked).onClick(async () => {
      var _a, _b;
      button.setDisabled(true);
      try {
        await signInBillingAccount(adapter, password, "connect");
        password = "";
        new import_obsidian2.Notice(adapter.state.billingRegistrationPending ? "Check your email and follow the verification link, then Connect again." : `Connected as ${adapter.state.billingEmail}.`);
        (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
      } catch (error) {
        new import_obsidian2.Notice(error instanceof Error ? error.message : "Connection failed. Please try again.");
        (_b = adapter.refresh) == null ? void 0 : _b.call(adapter);
      } finally {
        button.setDisabled(adapter.state.billingAccountLinked);
      }
    });
  }).addButton((button) => button.setButtonText("Sign out").setDisabled(!adapter.state.billingAccessToken).onClick(async () => {
    var _a;
    const refreshToken = adapter.state.billingRefreshToken;
    clearBillingSession(adapter.state);
    state.billingRegistrationPending = false;
    await adapter.persist();
    if (refreshToken) void (0, import_obsidian2.requestUrl)({ url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/logout`, method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refresh_token: refreshToken }), throw: false }).catch(() => {
    });
    new import_obsidian2.Notice("Signed out.");
    (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
  }));
  if (!adapter.state.billingAccountLinked) new import_obsidian2.Setting(section).setName("Forgot password?").setDesc("Reset your billing account password on Constance.").addButton((button) => button.setButtonText("Open reset page").onClick(() => window.open(`${CONSTANCE_ACCOUNT_BASE_URL}/password-reset`, "_blank")));
  const firstHeading = containerEl.querySelector(":scope > h1, :scope > h2");
  if (firstHeading == null ? void 0 : firstHeading.nextSibling) containerEl.insertBefore(section, firstHeading.nextSibling);
  else containerEl.prepend(section);
  queueMicrotask(() => {
    const candidates = Array.from(containerEl.querySelectorAll(":scope > .setting-item"));
    for (const item of candidates) {
      const label = item.textContent || "";
      if (/buy|checkout|refresh balance|sync balance|credit pack/i.test(label)) section.appendChild(item);
    }
    for (const summary of Array.from(containerEl.querySelectorAll('[class*="credit"][class*="summary"], [class*="balance"][class*="summary"]'))) {
      if (!section.contains(summary)) section.appendChild(summary);
    }
  });
}

// publish/preview-gateway.ts
var BASE = "https://app.tutivsoft.com/api/v1";
var codePoints = (text) => Array.from(text).length;
var hosts = /* @__PURE__ */ new WeakMap();
function configureGateway(settings, host) {
  hosts.set(settings, host);
}
function gatewayFor(settings) {
  const host = hosts.get(settings);
  if (!host) throw new Error("Managed execution is not initialized.");
  return host;
}
var digestPattern = /^[a-f0-9]{64}$/;
var previewQuoteResultPlaceholder = "0".repeat(64);
function canonical(value) {
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
  if (value && typeof value === "object") return "{" + Object.keys(value).sort().map((key) => JSON.stringify(key) + ":" + canonical(value[key])).join(",") + "}";
  return JSON.stringify(value);
}
function sameDimensions(a, b) {
  return !!a && !!b && canonical(a) === canonical(b);
}
function validateQuote(quote, expected) {
  var _a;
  if (!quote || !Number.isSafeInteger(quote.amount) || quote.amount < 1 || !Number.isSafeInteger(quote.free_units) || quote.free_units < 0 || !Number.isSafeInteger(quote.paid_units) || quote.paid_units < 0 || quote.free_units + quote.paid_units !== quote.amount || ((_a = quote.legacy_units) != null ? _a : 0) !== 0 || quote.retained_access === true) throw new Error("Invalid AI allowance split; this app requires an exact free/paid quote with no legacy or retained-access units.");
  for (const key of ["event_id", "app_id", "installation_id", "source_digest", "result_digest", "amount"]) if ((expected == null ? void 0 : expected[key]) !== void 0 && quote[key] !== expected[key]) throw new Error("Allowance quote identity conflicts with this exact operation.");
  if ((expected == null ? void 0 : expected.dimensions) && quote.dimensions !== void 0 && !sameDimensions(expected.dimensions, quote.dimensions)) throw new Error("Allowance quote dimensions conflict with this exact operation.");
}
function validateGenerationQuote(quote, request, host) {
  validateQuote(quote, { event_id: request.event_id, app_id: host.appId, installation_id: host.installationId, result_digest: previewQuoteResultPlaceholder });
  if (typeof quote.source_digest !== "string" || !digestPattern.test(quote.source_digest) || !quote.dimensions || typeof quote.dimensions !== "object" || Array.isArray(quote.dimensions)) throw new Error("Managed quote is missing canonical source or dimensions.");
}
function validateManagedPreview(preview, request, quote, host) {
  var _a;
  if (!preview || preview.event_id !== request.event_id || !Number.isSafeInteger(preview.amount) || preview.amount < 1 || typeof preview.source_digest !== "string" || !digestPattern.test(preview.source_digest) || typeof preview.result_digest !== "string" || !digestPattern.test(preview.result_digest) || !preview.dimensions || typeof preview.dimensions !== "object" || Array.isArray(preview.dimensions)) throw new Error("Managed preview identity or digest is incomplete. The exact preview was not accepted.");
  if (quote && (preview.source_digest !== quote.source_digest || preview.amount !== quote.amount || !sameDimensions(preview.dimensions, quote.dimensions))) throw new Error("Managed preview does not match the confirmed server quote. Preserve it and reconcile; no new generation was started.");
  const expectedAad = new TextEncoder().encode(`${host.appId}
${request.event_id}`), aad = decode(((_a = preview.envelope) == null ? void 0 : _a.aad) || "");
  if (aad.length !== expectedAad.length || aad.some((b, i) => b !== expectedAad[i])) throw new Error("Managed preview is bound to another app or event.");
}
function decode(value) {
  const raw = atob(value);
  const out = new Uint8Array(new ArrayBuffer(raw.length));
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}
async function digest(value) {
  const bytes = typeof value === "string" ? new TextEncoder().encode(value) : value;
  return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)), (b) => b.toString(16).padStart(2, "0")).join("");
}
async function send2(host, path, body, authenticated = false) {
  var _a, _b, _c, _d;
  const headers = { "Content-Type": "application/json" };
  if (authenticated && !host.state.billingAccessToken && host.state.billingRefreshToken) await refreshBillingSession(host.state, host.persist);
  if (host.state.billingAccessToken) headers.Authorization = `Bearer ${host.state.billingAccessToken}`;
  const request = () => (0, import_obsidian3.requestUrl)({ url: `${BASE}${path}`, method: body ? "POST" : "GET", headers, body: body ? JSON.stringify(body) : void 0, throw: false });
  let response = await request();
  if (response.status === 401 && host.state.billingRefreshToken && await refreshBillingSession(host.state, host.persist)) {
    headers.Authorization = `Bearer ${host.state.billingAccessToken}`;
    response = await request();
  }
  if (response.status < 200 || response.status >= 300) throw new Error(((_b = (_a = response.json) == null ? void 0 : _a.detail) == null ? void 0 : _b.message) || (typeof ((_c = response.json) == null ? void 0 : _c.detail) === "string" ? response.json.detail : `Managed service unavailable (HTTP ${response.status}).`));
  return (_d = response.json) == null ? void 0 : _d.data;
}
async function credential(host) {
  if (host.state.previewInstallationCredential) return host.state.previewInstallationCredential;
  const data = await send2(host, "/public/installations", { app_id: host.appId, installation_id: host.installationId });
  if (!(data == null ? void 0 : data.installation_credential)) throw new Error("Installation verification unavailable.");
  host.state.previewInstallationCredential = data.installation_credential;
  await host.persist();
  return data.installation_credential;
}
var memory = /* @__PURE__ */ new WeakMap();
async function managedText(host, input, operation, dimensions = {}, image) {
  const proof = await credential(host);
  let jobs = memory.get(host.state);
  if (!jobs) {
    jobs = /* @__PURE__ */ new Map();
    memory.set(host.state, jobs);
  }
  const id = await digest(JSON.stringify({ input, operation, dimensions, image }));
  let job = jobs.get(id);
  if (job == null ? void 0 : job.validationError) throw new Error(job.validationError);
  if (!job) {
    const event_id = `preview_${crypto.randomUUID()}`;
    const request = { app_id: host.appId, installation_id: host.installationId, installation_credential: proof, event_id, input, operation, dimensions, image };
    let quote;
    if (host.state.billingAccountLinked && (host.state.billingAccessToken || host.state.billingRefreshToken)) {
      quote = await send2(host, "/billing/previews/quote", request, true);
      validateGenerationQuote(quote, request, host);
      if (quote.allowed === false) throw new Error(quote.reason || "Allowance unavailable. Choose a smaller selection or purchase; input was not truncated.");
      if (!await new SplitModal(host, quote).wait()) throw new Error("Generation cancelled before provider dispatch.");
      request.expected_free_units = quote.free_units;
      request.expected_paid_units = quote.paid_units;
    }
    const preview = await send2(host, "/public/previews", request);
    job = { preview, validationError: "Managed preview identity is unverified. Keep it in memory and contact support; this result cannot be revealed or regenerated." };
    jobs.set(id, job);
    try {
      if (!(preview == null ? void 0 : preview.envelope) || !preview.job_token) throw new Error("Incomplete managed preview response.");
      validateManagedPreview(preview, request, quote, host);
      job.validationError = void 0;
    } catch (error) {
      job.validationError = error instanceof Error ? error.message : "Managed preview identity is unverified.";
      throw error;
    }
  }
  if (job.full && job.owner === host.state.billingEmail && host.state.billingAccountLinked && host.state.billingAccessToken) return job.full;
  const full = await new PreservedPreviewModal(host, job.preview, proof, job.preview.dimensions).wait();
  job.full = full;
  job.owner = host.state.billingEmail;
  return full;
}
var PreservedPreviewModal = class extends import_obsidian3.Modal {
  constructor(host, preview, proof, dimensions) {
    super(host.app);
    this.host = host;
    this.preview = preview;
    this.proof = proof;
    this.dimensions = dimensions;
    this.settled = false;
  }
  wait() {
    const result = new Promise((resolve, reject) => {
      this.resolve = resolve;
      this.reject = reject;
    });
    this.open();
    return result;
  }
  onOpen() {
    const root = this.contentEl;
    root.createEl("h2", { text: "Preserved preview" });
    root.createEl("p", { text: "Keep this window and Obsidian open while registering or buying. The exact result stays only in memory. Full reveal uses allowance once; later apply or save is free." });
    const sample = root.createEl("pre", { text: Array.from(this.preview.sample).slice(0, 500).join("") });
    sample.style.whiteSpace = "pre-wrap";
    root.createEl("p", { text: `Estimated native units: ${this.preview.amount}. Constance verifies your lifetime allowance and paid balance before full reveal.` });
    const status = root.createEl("p");
    addBillingAccountSettings(root, { state: this.host.state, appId: this.host.appId, installationId: this.host.installationId, persist: this.host.persist, syncBalance: async () => {
    }, refresh: () => {
      status.setText("Account updated. Reveal the same preview when verified.");
    } });
    addLivePacks(root, this.host);
    const reveal = root.createEl("button", { text: "Authorize and reveal exact result", cls: "mod-cta" });
    let quoted = false;
    let quotedOwner = "";
    let confirmedSplit;
    reveal.onclick = async () => {
      reveal.disabled = true;
      try {
        if (!this.host.state.billingAccessToken && !this.host.state.billingRefreshToken) throw new Error("Register, verify your email, and connect here first. Your preview is preserved.");
        if (!quoted || quotedOwner !== this.host.state.billingEmail) {
          const operation = { app_id: this.host.appId, installation_id: this.host.installationId, installation_credential: this.proof, event_id: this.preview.event_id, amount: this.preview.amount, source_digest: this.preview.source_digest, result_digest: this.preview.result_digest, dimensions: this.dimensions };
          const quote = await send2(this.host, "/billing/operations/quote", operation, true);
          validateQuote(quote, operation);
          if (quote.allowed === false) throw new Error(quote.reason || "Allowance unavailable. The preview is preserved; choose a smaller selection or purchase.");
          status.setText(`Confirm full reveal: ${quote.free_units} free + ${quote.paid_units} paid ${quote.amount} native units. This is one successful useful operation.`);
          confirmedSplit = quote;
          quoted = true;
          quotedOwner = this.host.state.billingEmail;
          reveal.setText("Confirm split and reveal exact result");
          return;
        }
        const nonce = decode(this.preview.envelope.nonce), ciphertext = decode(this.preview.envelope.ciphertext), joined = new Uint8Array(new ArrayBuffer(nonce.length + ciphertext.length));
        joined.set(nonce);
        joined.set(ciphertext, nonce.length);
        const envelope_digest = await digest(joined);
        if (envelope_digest !== this.preview.envelope_digest) throw new Error("Preview integrity check failed.");
        if (this.preview.envelope.algorithm !== "AES-GCM" || nonce.length !== 12 || ciphertext.length < 16) throw new Error("Invalid preview encryption metadata.");
        const expected = new TextEncoder().encode(`${this.host.appId}
${this.preview.event_id}`), aad = decode(this.preview.envelope.aad);
        if (aad.length !== expected.length || aad.some((b, i) => b !== expected[i])) throw new Error("Preview belongs to another operation.");
        const result = await send2(this.host, `/billing/previews/${encodeURIComponent(this.preview.job_token)}/reveal`, { app_id: this.host.appId, installation_id: this.host.installationId, installation_credential: this.proof, event_id: this.preview.event_id, envelope_digest, expected_free_units: confirmedSplit.free_units, expected_paid_units: confirmedSplit.paid_units }, true);
        if (this.preview.envelope.algorithm !== "AES-GCM") throw new Error("Unsupported preview encryption.");
        if ((result == null ? void 0 : result.event_id) && result.event_id !== this.preview.event_id) throw new Error("Preview authorization belongs to a different operation.");
        if ((result == null ? void 0 : result.state) !== "committed" || result.result_digest !== this.preview.result_digest) throw new Error("Reveal authorization is not committed.");
        const key = await crypto.subtle.importKey("raw", decode(result.key), "AES-GCM", false, ["decrypt"]);
        const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: nonce, additionalData: aad }, key, ciphertext);
        const text = new TextDecoder("utf-8", { fatal: true }).decode(plain);
        if (await digest(text) !== this.preview.result_digest) throw new Error("Result integrity check failed.");
        this.host.state.previewCompletionJournal = { event_id: this.preview.event_id, result_digest: this.preview.result_digest, state: "committed", owner: this.host.state.billingEmail };
        await this.host.persist();
        this.settled = true;
        this.resolve(text);
        this.close();
      } catch (error) {
        quoted = false;
        reveal.setText("Refresh allowance split");
        status.setText(error instanceof Error ? error.message : "Authorization failed. Preview is preserved.");
      } finally {
        reveal.disabled = false;
      }
    };
  }
  onClose() {
    if (!this.settled) {
      this.settled = true;
      this.reject(new Error("Preview closed. No source changes were applied."));
    }
    this.contentEl.empty();
  }
};
function joinCurrentPacks(config, live, appId = config == null ? void 0 : config.app_id) {
  const configured = Array.isArray(config == null ? void 0 : config.one_time_packs) ? config.one_time_packs : [];
  const prices = Array.isArray(live == null ? void 0 : live[appId]) ? live[appId] : [];
  const unit = typeof (config == null ? void 0 : config.credit_unit_name) === "string" && config.credit_unit_name.trim() ? config.credit_unit_name.trim() : "credits";
  return configured.map((pack) => {
    const priceId = typeof pack.price_id === "string" ? pack.price_id : "";
    const price = priceId ? prices.find((item) => (item == null ? void 0 : item.price_id) === priceId && (item == null ? void 0 : item.interval) === "one_time") : void 0;
    const units = Number(pack.credits);
    const available = !!priceId && Number.isSafeInteger(units) && units > 0 && (price == null ? void 0 : price.status) === "active" && price.checkout_available === true && typeof price.amount === "string" && price.amount.length > 0 && (!pack.product_id || price.product_id === pack.product_id);
    return { pack, price, priceId, units, unit, available };
  });
}
function addLivePacks(root, host) {
  const section = root.createDiv();
  const status = section.createEl("p", { text: "Loading current Paddle prices\u2026" });
  void Promise.all([
    send2(host, `/apps/${encodeURIComponent(host.appId)}/billing-config`),
    send2(host, `/billing/live-prices?app_ids=${encodeURIComponent(host.appId)}`)
  ]).then(([config, live]) => {
    const offers = joinCurrentPacks(config, live, host.appId);
    if (!offers.length) throw new Error("No configured one-time offers.");
    status.setText("Current provider pricing. Final checkout calculates applicable tax.");
    for (const { pack, price, priceId, units, unit, available } of offers) {
      const description = [price == null ? void 0 : price.description, Number.isSafeInteger(units) && units > 0 ? `${units.toLocaleString()} ${unit}` : "", available ? "" : (price == null ? void 0 : price.checkout_unavailable_reason) || "Current price unavailable"].filter(Boolean).join(" \xB7 ");
      const row = new import_obsidian3.Setting(section).setName(pack.name || pack.code || "One-time offer").setDesc(description);
      row.addButton((button) => button.setButtonText(available ? `Buy ${price.amount}` : "Pricing unavailable").setDisabled(!available).onClick(async () => {
        var _a, _b, _c;
        button.setDisabled(true);
        try {
          let pending = host.state.previewPendingCheckout;
          if ((pending == null ? void 0 : pending.owner) && pending.owner !== host.state.billingEmail) throw new Error("Sign in to the account owning the pending purchase.");
          if (pending == null ? void 0 : pending.checkout_id) {
            const status2 = await send2(host, `/billing/checkouts/${encodeURIComponent(pending.checkout_id)}`, void 0, true);
            if (status2.settled === true || ["completed", "canceled", "cancelled", "failed", "expired"].includes(status2.status)) {
              host.state.previewPendingCheckout = void 0;
              await host.persist();
              pending = void 0;
            }
          }
          if (pending && pending.price_id && pending.price_id !== priceId) throw new Error("A purchase is pending. Resolve its status before another purchase.");
          const legacyPlan = pending && !pending.price_id ? pending.plan_code : void 0;
          const request = pending || { price_id: priceId, idempotency_key: `checkout_${crypto.randomUUID()}`, owner: host.state.billingEmail };
          host.state.previewPendingCheckout = request;
          await host.persist();
          if (!host.state.billingAccessToken) await refreshBillingSession(host.state, host.persist);
          const oldCheckout = !!legacyPlan;
          const response = await (0, import_obsidian3.requestUrl)({ url: `${BASE}/billing/${oldCheckout ? "checkout" : "checkout-price"}`, method: "POST", headers: { Authorization: `Bearer ${host.state.billingAccessToken}`, "Content-Type": "application/json", "Idempotency-Key": request.idempotency_key }, body: JSON.stringify(oldCheckout ? { app_id: host.appId, installation_id: host.installationId, plan_code: legacyPlan, quantity: 1 } : { app_id: host.appId, installation_id: host.installationId, price_id: request.price_id, quantity: 1 }), throw: false });
          if (response.status < 200 || response.status >= 300) throw new Error(((_b = (_a = response.json) == null ? void 0 : _a.detail) == null ? void 0 : _b.message) || "Checkout unavailable; refresh current prices.");
          const checkout = (_c = response.json) == null ? void 0 : _c.data;
          if (!(checkout == null ? void 0 : checkout.checkout_id)) throw new Error("Checkout is still being confirmed; retry the same purchase to recover it safely.");
          request.checkout_id = String(checkout.checkout_id);
          await host.persist();
          if (typeof checkout.checkout_url === "string" && checkout.checkout_url) window.open(checkout.checkout_url, "_blank", "noopener");
          else new import_obsidian3.Notice("Checkout is still being confirmed. Its status will refresh when you return.");
        } catch (error) {
          new import_obsidian3.Notice(error instanceof Error ? error.message : "Checkout unavailable.");
        } finally {
          button.setDisabled(!available);
        }
      }));
    }
  }).catch(() => status.setText("Pricing temporarily unavailable. Your preview remains available; buying is disabled."));
}
var SplitModal = class extends import_obsidian3.Modal {
  constructor(host, quote) {
    super(host.app);
    this.host = host;
    this.quote = quote;
    this.settled = false;
  }
  wait() {
    const result = new Promise((resolve) => this.resolve = resolve);
    this.open();
    return result;
  }
  onOpen() {
    this.contentEl.createEl("h2", { text: "Confirm allowance" });
    this.contentEl.createEl("p", { text: `${this.quote.free_units} free + ${this.quote.paid_units} paid native units${this.quote.legacy_units ? ` + ${this.quote.legacy_units} existing ${this.quote.legacy_unit}` : ""}. Free completion counts once toward your lifetime starter allowance; paid work preserves exhausted trial limits.` });
    this.contentEl.createEl("button", { text: "Confirm", cls: "mod-cta" }).onclick = () => {
      this.settled = true;
      this.resolve(true);
      this.close();
    };
  }
  onClose() {
    if (!this.settled) this.resolve(false);
    this.contentEl.empty();
  }
};

// publish/main.ts
var import_obsidian6 = require("obsidian");

// publish/plugin-support.ts
var import_obsidian4 = require("obsidian");
var SAFE_DETAIL_KEYS = /* @__PURE__ */ new Set([
  "version",
  "operation",
  "scope",
  "selectedCount",
  "total",
  "changed",
  "skipped",
  "failed",
  "unchanged",
  "reviewEnabled",
  "fieldCount",
  "noteChars",
  "httpStatus",
  "errorType",
  "outcome",
  "restored",
  "authorizationSource",
  "cancelled",
  "line",
  "column",
  "settingCount",
  "attempt",
  "attempts",
  "queueCount",
  "itemCount",
  "fileCount",
  "imageCount",
  "stage",
  "category",
  "status",
  "durationMs",
  "elapsedMs"
]);
function safeString(value) {
  if (value.length <= 120 && /^[A-Za-z0-9 _=.,:-]*$/.test(value) && !/(?:sk-[A-Za-z0-9]|bearer|api.?key|token|secret)/i.test(value)) {
    return value;
  }
  return "[omitted]";
}
function safeDetail(value) {
  if (value instanceof Error) return JSON.stringify({ errorType: safeString(value.name || "Error") });
  if (!value || typeof value !== "object" || Array.isArray(value)) return "[detail omitted]";
  const safe = {};
  for (const [key, item] of Object.entries(value)) {
    if (!SAFE_DETAIL_KEYS.has(key)) continue;
    if (typeof item === "string") safe[key] = safeString(item);
    else if (typeof item === "number" && Number.isFinite(item)) safe[key] = item;
    else if (typeof item === "boolean" || item === null) safe[key] = item;
  }
  return JSON.stringify(safe);
}
function safeErrorType(error) {
  if (error instanceof Error) return safeString(error.name || "Error");
  return safeString(typeof error);
}
var DocumentationModal = class extends import_obsidian4.Modal {
  constructor(app, docs) {
    super(app);
    this.docs = docs;
  }
  onOpen() {
    this.titleEl.setText(this.docs.name + " documentation");
    this.contentEl.createEl("p", { text: this.docs.summary });
    const addSection = (title, items) => {
      this.contentEl.createEl("h3", { text: title });
      const list = this.contentEl.createEl("ol");
      for (const item of items) list.createEl("li", { text: item });
    };
    addSection("Quick start", this.docs.quickStart);
    addSection("Useful commands", Array.from(/* @__PURE__ */ new Set([...this.docs.commands, "Copy full debug log"])));
    addSection("Troubleshooting", this.docs.troubleshooting);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PluginSupport = class {
  constructor(plugin, docs) {
    this.plugin = plugin;
    this.docs = docs;
    this.entries = [];
    this.maxEntries = 1e3;
    this.droppedEntries = 0;
    this.started = false;
  }
  start() {
    if (this.started) return;
    this.started = true;
    this.info("plugin.loaded", { version: this.plugin.manifest.version });
    this.plugin.registerDomEvent(window, "error", (event) => {
      const error = event.error;
      this.error("runtime.error", {
        errorType: error instanceof Error ? error.name : "ErrorEvent",
        line: event.lineno,
        column: event.colno
      });
    });
    this.plugin.registerDomEvent(window, "unhandledrejection", (event) => {
      this.error("runtime.unhandled_rejection", { errorType: safeErrorType(event.reason) });
    });
    const addCommand = this.plugin.addCommand.bind(this.plugin);
    const registerCommand = (command) => addCommand(this.instrumentCommand(command));
    registerCommand({
      id: "open-documentation",
      name: "Open documentation",
      callback: () => new DocumentationModal(this.plugin.app, this.docs).open()
    });
    registerCommand({
      id: "copy-debug-log",
      name: "Copy full debug log",
      callback: () => this.copyDiagnostics()
    });
    registerCommand({
      id: "open-plugin-settings",
      name: "Open plugin settings",
      callback: () => {
        const setting = this.plugin.app.setting;
        setting == null ? void 0 : setting.open();
        setting == null ? void 0 : setting.openTabById(this.plugin.manifest.id);
      }
    });
    this.instrumentFutureCommands(addCommand);
  }
  info(event, detail) {
    this.record("info", event, detail);
  }
  warn(event, detail) {
    this.record("warn", event, detail);
  }
  error(event, detail) {
    this.record("error", event, detail);
  }
  addDiagnosticsSetting(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Diagnostics").setDesc("Copy up to the latest 1,000 events recorded by this plugin. Logs reset when the plugin reloads. Note contents, paths, credentials, and raw error messages are excluded.").addButton((button) => button.setButtonText("Copy full log").onClick(() => {
      void this.copyDiagnostics();
    }));
  }
  instrumentFutureCommands(addCommand) {
    const originalDescriptor = Object.getOwnPropertyDescriptor(this.plugin, "addCommand");
    Object.defineProperty(this.plugin, "addCommand", {
      configurable: true,
      writable: true,
      value: (command) => addCommand(this.instrumentCommand(command))
    });
    this.plugin.register(() => {
      if (originalDescriptor) Object.defineProperty(this.plugin, "addCommand", originalDescriptor);
      else Reflect.deleteProperty(this.plugin, "addCommand");
    });
  }
  instrumentCommand(command) {
    const instrument = (callback) => (...args) => this.trackCommand(command.id, () => callback.apply(command, args));
    return {
      ...command,
      callback: command.callback ? instrument(command.callback) : void 0,
      editorCallback: command.editorCallback ? instrument(command.editorCallback) : void 0,
      checkCallback: command.checkCallback ? (checking) => checking ? command.checkCallback(checking) : this.trackCommand(command.id, () => command.checkCallback(checking)) : void 0,
      editorCheckCallback: command.editorCheckCallback ? (checking, editor, context) => checking ? command.editorCheckCallback(checking, editor, context) : this.trackCommand(command.id, () => command.editorCheckCallback(checking, editor, context)) : void 0
    };
  }
  trackCommand(commandId, action) {
    const startedAt = Date.now();
    this.info("command.started", { operation: commandId });
    try {
      const result = action();
      if (result && typeof result.then === "function") {
        return Promise.resolve(result).then(
          (value) => {
            this.info("command.completed", { operation: commandId, durationMs: Date.now() - startedAt });
            return value;
          },
          (error) => {
            this.error("command.failed", { operation: commandId, errorType: safeErrorType(error), durationMs: Date.now() - startedAt });
            throw error;
          }
        );
      }
      this.info("command.completed", { operation: commandId, durationMs: Date.now() - startedAt });
      return result;
    } catch (error) {
      this.error("command.failed", { operation: commandId, errorType: safeErrorType(error), durationMs: Date.now() - startedAt });
      throw error;
    }
  }
  record(level, event, detail) {
    var _a;
    const safeEvent = /^[a-z0-9][a-z0-9._-]{0,99}$/i.test(event) ? event : "invalid_event";
    const entry = { at: (/* @__PURE__ */ new Date()).toISOString(), level, event: safeEvent };
    if (detail !== void 0) entry.detail = safeDetail(detail);
    this.entries.push(entry);
    if (this.entries.length > this.maxEntries) {
      const removed = this.entries.length - this.maxEntries;
      this.entries.splice(0, removed);
      this.droppedEntries += removed;
    }
    const method = level === "error" ? console.error : level === "warn" ? console.warn : console.info;
    method.call(console, "[" + this.docs.name + "] " + entry.event, (_a = entry.detail) != null ? _a : "");
  }
  async copyDiagnostics() {
    this.info("diagnostics.copy_requested", { total: this.entries.length + 1 });
    const captured = (/* @__PURE__ */ new Date()).toISOString();
    const snapshot = this.entries.slice();
    const header = [
      "Plugin debug log",
      "Log scope: this plugin, since its most recent load",
      "Plugin: " + this.docs.name,
      "Plugin ID: " + this.plugin.manifest.id,
      "Version: " + this.plugin.manifest.version,
      "Captured: " + captured,
      "User agent: " + navigator.userAgent,
      "Events included: " + snapshot.length,
      "Older events omitted: " + this.droppedEntries,
      ""
    ];
    const text = header.concat(snapshot.map(
      (entry) => entry.at + " [" + entry.level.toUpperCase() + "] " + entry.event + (entry.detail ? " \u2014 " + entry.detail : "")
    )).join("\n");
    try {
      await navigator.clipboard.writeText(text);
      this.info("diagnostics.copy_succeeded", { total: snapshot.length });
      const omitted = this.droppedEntries ? "; " + this.droppedEntries + " older events omitted" : "";
      new import_obsidian4.Notice(this.docs.name + ": copied " + snapshot.length + " log events" + omitted + ".");
    } catch (error) {
      this.error("diagnostics.copy_failed", { errorType: safeErrorType(error) });
      new import_obsidian4.Notice(this.docs.name + ": could not copy the debug log.");
    }
  }
};

// publish/ai-request-queue.ts
var import_obsidian5 = require("obsidian");
var AiRequestQueue = class extends import_obsidian5.Modal {
  constructor(app, appName) {
    super(app);
    this.appName = appName;
    this.pending = [];
    this.active = null;
    this.running = false;
    this.opened = false;
    this.nextId = 1;
    this.timer = null;
    this.lastCompletion = "";
  }
  onOpen() {
    this.opened = true;
    this.startTimer();
    this.render();
  }
  onClose() {
    this.opened = false;
    if (this.timer !== null) window.clearInterval(this.timer);
    this.timer = null;
    this.contentEl.empty();
  }
  enqueue(label, submittedText, run) {
    return new Promise((resolve) => {
      const job = {
        id: this.nextId++,
        label,
        submittedText,
        queuedAt: Date.now(),
        statusLabel: "Waiting",
        run,
        resolve
      };
      this.pending.push(job);
      if (!this.opened) this.open();
      this.render();
      void this.drain();
    });
  }
  startTimer() {
    if (this.timer !== null) window.clearInterval(this.timer);
    this.timer = window.setInterval(() => this.render(), 1e3);
  }
  async drain() {
    if (this.running) return;
    this.running = true;
    try {
      while (this.pending.length) {
        const job = this.pending.shift();
        this.active = job;
        job.startedAt = Date.now();
        job.statusLabel = "Preparing request";
        this.render();
        const report = (update) => {
          var _a;
          if (((_a = this.active) == null ? void 0 : _a.id) !== job.id) return;
          if (update.label !== void 0) job.statusLabel = update.label;
          if (update.submittedText !== void 0) job.submittedText = update.submittedText;
          if (update.current !== void 0) job.current = update.current;
          if (update.total !== void 0) job.total = update.total;
          this.render();
        };
        try {
          const value = await job.run(report);
          const elapsed = Math.max(0, Math.floor((Date.now() - job.startedAt) / 1e3));
          this.lastCompletion = `${job.label} completed in ${elapsed} second${elapsed === 1 ? "" : "s"}.`;
          new import_obsidian5.Notice(`${this.appName}: ${this.lastCompletion}`, 4e3);
          job.resolve({ status: "completed", value });
        } catch (error) {
          const elapsed = Math.max(0, Math.floor((Date.now() - job.startedAt) / 1e3));
          const detail = error instanceof Error ? error.message : "Unknown error";
          this.lastCompletion = `${job.label} failed after ${elapsed} second${elapsed === 1 ? "" : "s"}: ${detail}`;
          new import_obsidian5.Notice(`${this.appName}: ${job.label} failed. ${detail}`, 6e3);
          job.resolve({ status: "failed", error });
        } finally {
          this.active = null;
          this.render();
        }
      }
    } finally {
      this.running = false;
    }
  }
  clearWaiting() {
    const removed = this.pending.splice(0);
    for (const job of removed) job.resolve({ status: "cleared" });
    if (removed.length) {
      this.lastCompletion = `${removed.length} waiting AI request${removed.length === 1 ? " was" : "s were"} removed.`;
      new import_obsidian5.Notice(`${this.appName}: cleared ${removed.length} waiting AI request${removed.length === 1 ? "" : "s"}.`, 4e3);
      this.render();
    }
  }
  render() {
    var _a;
    if (!this.opened) return;
    const root = this.contentEl;
    root.empty();
    root.createEl("h2", { text: `${this.appName} AI request queue` });
    if (this.active) {
      const elapsed = Math.max(0, Math.floor((Date.now() - ((_a = this.active.startedAt) != null ? _a : Date.now())) / 1e3));
      const active = root.createDiv();
      active.createEl("h3", { text: `Processing: ${this.active.label}` });
      active.createEl("p", { text: `${this.active.statusLabel} \xB7 ${elapsed} second${elapsed === 1 ? "" : "s"} elapsed${this.active.current && this.active.total ? ` \xB7 ${this.active.current}/${this.active.total}` : ""}` });
      active.createEl("p", { text: "Text sent to AI (excerpt)" });
      const excerpt = active.createEl("pre", { text: this.active.submittedText.trim().slice(0, 320) || "Preparing the text to send\u2026" });
      excerpt.style.whiteSpace = "pre-wrap";
      excerpt.style.maxHeight = "12em";
      excerpt.style.overflow = "auto";
    } else {
      root.createEl("p", { text: "No AI request is processing." });
    }
    root.createEl("h3", { text: `Waiting (${this.pending.length})` });
    if (!this.pending.length) root.createEl("p", { text: "The waiting queue is empty." });
    for (const [index, job] of this.pending.entries()) {
      const item = root.createDiv();
      item.createEl("p", { text: `${index + 1}. ${job.label}` });
      item.createEl("pre", { text: job.submittedText.trim().slice(0, 180) || "Text will be shown when this request starts." }).style.whiteSpace = "pre-wrap";
    }
    if (this.lastCompletion) root.createEl("p", { text: this.lastCompletion });
    const footer = root.createDiv();
    new import_obsidian5.ButtonComponent(footer).setButtonText("Clear waiting requests").setWarning().setDisabled(this.pending.length === 0).onClick(() => this.clearWaiting());
    new import_obsidian5.ButtonComponent(footer).setButtonText("Close").onClick(() => this.close());
    root.createEl("p", { text: "Clearing removes waiting requests. The active request will finish." }).style.color = "var(--text-muted)";
  }
};

// publish/main.ts
var DEFAULT_MODEL = "~deepseek/deepseek-v4-flash-latest";
var CONSTANCE_BASE_URL = "https://app.tutivsoft.com";
var CONSTANCE_APP_ID = "culebra-ai-spell-correct";
function generateSecureDeviceId() {
  const bytes = new Uint8Array(16);
  window.crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
function generateEventId() {
  const bytes = new Uint8Array(12);
  window.crypto.getRandomValues(bytes);
  return "evt_" + Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
async function fetchConstanceEntitlements(plugin) {
  var _a;
  if (!plugin.settings.billingAccessToken || !plugin.settings.billingAccountLinked) return null;
  const query = new URLSearchParams({ app_id: CONSTANCE_APP_ID, installation_id: plugin.settings.constanceDeviceId });
  const response = await requestAuthenticatedBilling(plugin.settings, () => plugin.saveSettings(), {
    url: `${CONSTANCE_BASE_URL}/api/v1/billing/entitlements/me?${query.toString()}`,
    method: "GET",
    throw: false
  });
  if (response.status === 401 || response.status === 403 || response.status === 404) {
    clearBillingSession(plugin.settings);
    await plugin.saveSettings();
  }
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Entitlement sync failed: HTTP ${response.status}`);
  }
  return (_a = response.json) == null ? void 0 : _a.data;
}
async function spendConstanceCredits(plugin, amount, stableEventId) {
  const result = await spendAccountCredits(plugin.settings, () => plugin.saveSettings(), CONSTANCE_APP_ID, plugin.settings.constanceDeviceId, stableEventId, amount);
  if (result.kind === "ok" || result.kind === "insufficient" || result.kind === "error") return result;
  clearBillingSession(plugin.settings);
  await plugin.saveSettings();
  return { kind: "error" };
}
async function syncPurchasedCreditsFromConstance(plugin, manual = false) {
  var _a, _b;
  resumeAccountCheckout({
    state: plugin.settings,
    appId: CONSTANCE_APP_ID,
    installationId: plugin.settings.constanceDeviceId,
    persist: () => plugin.saveSettings(),
    syncBalance: () => syncPurchasedCreditsFromConstance(plugin),
    refreshSession: () => refreshBillingSession(plugin.settings, () => plugin.saveSettings())
  });
  if (!plugin.settings.constanceDeviceId) {
    return;
  }
  try {
    const entitlement = await fetchConstanceEntitlements(plugin);
    const serverBalance = (_a = entitlement == null ? void 0 : entitlement.credits) == null ? void 0 : _a.balance;
    if (!Number.isFinite(serverBalance)) throw new Error("Billing returned an invalid balance");
    plugin.settings.freeCredits = Math.max(0, Number((_b = entitlement == null ? void 0 : entitlement.free_usage) == null ? void 0 : _b.remaining) || 0);
    plugin.settings.purchasedCredits = Math.max(0, Number(serverBalance) || 0);
    await plugin.saveSettings();
  } catch (error) {
    if (manual) throw error;
    console.error("Culebra: Constance entitlement sync failed", error);
  }
}
async function retryPendingSpendEvents(plugin) {
  var _a;
  const pending = [...(_a = plugin.settings.pendingSpendEvents) != null ? _a : []];
  for (const event of pending) {
    if (event.kind === "free") {
      const result2 = await claimAccountFreeUsage(plugin.settings, () => plugin.saveSettings(), CONSTANCE_APP_ID, plugin.settings.constanceDeviceId, event.eventId, event.amount);
      if (result2.kind === "error" || result2.kind === "auth-required") break;
      plugin.settings.pendingSpendEvents = plugin.settings.pendingSpendEvents.filter((item) => item.eventId !== event.eventId);
      if (result2.kind === "ok") plugin.settings.freeCredits = result2.remaining;
      await plugin.saveSettings();
      continue;
    }
    const result = await spendConstanceCredits(plugin, event.amount, event.eventId);
    if (result.kind === "error") break;
    plugin.settings.pendingSpendEvents = plugin.settings.pendingSpendEvents.filter((item) => item.eventId !== event.eventId);
    if (result.kind === "ok") plugin.settings.purchasedCredits = result.balance;
    else plugin.settings.purchasedCredits = 0;
    await plugin.saveSettings();
  }
}
var DEFAULT_SETTINGS = {
  settingsMode: "simple",
  model: DEFAULT_MODEL,
  apiKey: "",
  constanceDeviceId: "",
  billingEmail: "",
  billingAccessToken: "",
  billingRefreshToken: "",
  billingAccessExpiresAt: 0,
  billingAccountLinked: false,
  freeCredits: 0,
  purchasedCredits: 0,
  pendingSpendEvents: [],
  onboardingSeen: false,
  reviewBeforeApply: false
};
var CulebraSpellCorrectPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    this.support = new PluginSupport(this, { name: "Culebra AI Spell Correct", summary: "Correct selected text or an entire note with a one-action AI workflow.", quickStart: ["Sign in to billing in Settings.", "Select text or open a Markdown note.", "Run a Culebra correction command; edits apply automatically and can be undone."], commands: ["Correct selected text", "Correct current note", "Undo last correction"], troubleshooting: ["Use Copy debug log before reporting a problem.", "Confirm the note is editable and the billing account is linked."] });
    this.support.start();
    await this.loadSettings();
    this.aiQueue = new AiRequestQueue(this.app, "Culebra");
    if (!this.settings.constanceDeviceId) {
      this.settings.constanceDeviceId = generateSecureDeviceId();
      await this.saveSettings();
    }
    this.settings.pendingSpendEvents = Array.isArray(this.settings.pendingSpendEvents) ? this.settings.pendingSpendEvents.filter((item) => item && typeof item.eventId === "string" && Number.isInteger(item.amount) && item.amount > 0) : [];
    this.settings.billingAccessToken = typeof this.settings.billingAccessToken === "string" ? this.settings.billingAccessToken : "";
    this.settings.billingRefreshToken = typeof this.settings.billingRefreshToken === "string" ? this.settings.billingRefreshToken : "";
    this.settings.billingAccessExpiresAt = Number(this.settings.billingAccessExpiresAt) || 0;
    this.settings.billingAccountLinked = this.settings.billingAccountLinked === true && Boolean(this.settings.billingAccessToken);
    await this.saveSettings();
    if (!this.settings.onboardingSeen) {
      this.settings.onboardingSeen = true;
      await this.saveSettings();
    }
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const hasSelection = editor.getSelection().trim().length > 0;
        menu.addItem((item) => {
          item.setTitle(hasSelection ? "Culebra: Correct selected text" : "Culebra: Correct current note").setIcon("spell-check").onClick(() => {
            void this.correctEditorText(editor);
          });
        });
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian6.TFile) || file.extension !== "md") {
          return;
        }
        menu.addItem((item) => {
          item.setTitle("Culebra: Correct this Markdown file").setIcon("spell-check").onClick(() => {
            void this.correctFile(file);
          });
        });
      })
    );
    this.addCommand({
      id: "spell-correct",
      name: "Correct selection or current note",
      editorCallback: (editor) => this.correctEditorText(editor)
    });
    this.addCommand({ id: "show-ai-request-queue", name: "Show AI request queue", callback: () => this.aiQueue.open() });
    configureGateway(this.settings, { app: this.app, appId: CONSTANCE_APP_ID, installationId: this.settings.constanceDeviceId, state: this.settings, persist: () => this.saveSettings() });
    this.addSettingTab(new CulebraSettingTab(this.app, this));
    void syncPurchasedCreditsFromConstance(this).then(() => retryPendingSpendEvents(this));
  }
  async loadSettings() {
    const savedSettings = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedSettings);
    this.settings.settingsMode = this.settings.settingsMode === "advanced" ? "advanced" : "simple";
    this.settings.freeCredits = 0;
    if (savedSettings && typeof savedSettings.onboardingSeen !== "boolean") {
      this.settings.onboardingSeen = true;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  pollAfterCheckout(checkoutId) {
    let attempts = 0;
    const intervalId = window.setInterval(() => {
      attempts += 1;
      void (async () => {
        const settled = checkoutId ? await pollAuthenticatedCheckout({ state: this.settings, appId: CONSTANCE_APP_ID, installationId: this.settings.constanceDeviceId, persist: () => this.saveSettings(), syncBalance: () => syncPurchasedCreditsFromConstance(this) }, checkoutId).catch(() => false) : false;
        if (settled || !checkoutId) await syncPurchasedCreditsFromConstance(this);
        if (settled || attempts >= 6) window.clearInterval(intervalId);
      })();
    }, 15e3);
  }
  /**
  * Reserves the character-based cost only after the user approves a preview.
  * The local free-character pool is used first, followed by the Constance
   * balance; any unverified balance or spend blocks the edit until the
   * server gives an authoritative result.
   */
  async chargeOneCredit(textLength) {
    const cost = Math.max(1, Math.ceil(textLength));
    if (!this.settings.billingAccessToken || !this.settings.billingAccountLinked) {
      new import_obsidian6.Notice("Culebra: sign in or create a billing account in plugin settings before correcting text.");
      return false;
    }
    await retryPendingSpendEvents(this);
    if (this.settings.pendingSpendEvents.length > 0) {
      new import_obsidian6.Notice("Culebra: a previous billing operation is still being reconciled. No correction was applied.");
      return false;
    }
    const freeEventId = `free_${generateEventId()}`;
    this.settings.pendingSpendEvents.push({ eventId: freeEventId, amount: cost, kind: "free" });
    await this.saveSettings();
    const free = await claimAccountFreeUsage(this.settings, () => this.saveSettings(), CONSTANCE_APP_ID, this.settings.constanceDeviceId, freeEventId, cost);
    if (free.kind === "ok" || free.kind === "insufficient") {
      this.settings.pendingSpendEvents = this.settings.pendingSpendEvents.filter((item) => item.eventId !== freeEventId);
      await this.saveSettings();
    }
    if (free.kind === "ok") {
      this.settings.freeCredits = free.remaining;
      await this.saveSettings();
      return true;
    }
    if (free.kind === "auth-required") {
      clearBillingSession(this.settings);
      await this.saveSettings();
      new import_obsidian6.Notice("Culebra: your billing session expired. Sign in again.");
      return false;
    }
    if (free.kind === "error") {
      new import_obsidian6.Notice("Culebra: the account allowance could not be verified. No correction was applied.");
      return false;
    }
    await retryPendingSpendEvents(this);
    if (this.settings.pendingSpendEvents.length > 0) {
      new import_obsidian6.Notice("Culebra: a previous credit spend is still being reconciled. Please retry after the connection is restored.");
      return false;
    }
    const stableEventId = generateEventId();
    this.settings.pendingSpendEvents.push({ eventId: stableEventId, amount: cost });
    try {
      await this.saveSettings();
    } catch (error) {
      this.settings.pendingSpendEvents = this.settings.pendingSpendEvents.filter((item) => item.eventId !== stableEventId);
      console.error("Culebra: could not persist pending credit spend", error);
      return false;
    }
    const result = await spendConstanceCredits(this, cost, stableEventId);
    if (result.kind === "ok") {
      this.settings.purchasedCredits = result.balance;
      this.settings.pendingSpendEvents = this.settings.pendingSpendEvents.filter((item) => item.eventId !== stableEventId);
      await this.saveSettings();
      return true;
    }
    if (result.kind === "insufficient") {
      this.settings.purchasedCredits = 0;
      this.settings.pendingSpendEvents = this.settings.pendingSpendEvents.filter((item) => item.eventId !== stableEventId);
      await this.saveSettings();
      new import_obsidian6.Notice("Culebra: out of characters. Review current one-time offers in plugin settings.");
      return false;
    }
    console.warn("Culebra: credit spend is unknown; blocking until the persisted event can be reconciled.");
    new import_obsidian6.Notice("Culebra: billing could not be verified. Retry after the connection is restored.");
    return false;
  }
  /** Correct the current selection, or the whole active note when no text is selected. */
  async correctEditorText(editor) {
    const selection = editor.getSelection();
    const hasSelection = selection.trim().length > 0;
    const originalText = hasSelection ? selection : editor.getValue();
    const target = hasSelection ? "selection" : "current note";
    const correctedText = await this.correctText(originalText, target);
    if (!correctedText) {
      return;
    }
    if (correctedText === originalText) {
      new import_obsidian6.Notice(`Culebra found no changes in the ${target}.`);
      return;
    }
    if (this.settings.reviewBeforeApply && !await new CorrectionReviewModal(this.app, target, originalText, correctedText).waitForResult()) return;
    if (hasSelection ? editor.getSelection() !== originalText : editor.getValue() !== originalText) {
      new import_obsidian6.Notice("Culebra: the note changed during correction. Run the correction again to protect your edits.");
      return;
    }
    if (hasSelection ? editor.getSelection() !== originalText : editor.getValue() !== originalText) {
      new import_obsidian6.Notice("Culebra: the note changed during billing. Your edits were protected; contact support for a credit adjustment.");
      return;
    }
    if (hasSelection) {
      editor.replaceSelection(correctedText);
    } else {
      editor.setValue(correctedText);
    }
    new import_obsidian6.Notice(`Culebra corrected ${target}. Undo with Ctrl/Cmd+Z if needed.`);
  }
  /** Replace a Markdown file after optional Settings-based before/after review. */
  async correctFile(file) {
    const originalText = await this.app.vault.read(file);
    const correctedText = await this.correctText(originalText, file.name);
    if (!correctedText) {
      return;
    }
    if (correctedText === originalText) {
      new import_obsidian6.Notice(`Culebra found no changes in ${file.name}.`);
      return;
    }
    if (await this.app.vault.read(file) !== originalText) {
      new import_obsidian6.Notice(`Culebra: ${file.name} changed during correction. Run the correction again to protect your edits.`);
      return;
    }
    if (this.settings.reviewBeforeApply && !await new CorrectionReviewModal(this.app, file.name, originalText, correctedText).waitForResult()) return;
    if (await this.app.vault.read(file) !== originalText) {
      new import_obsidian6.Notice(`Culebra: ${file.name} changed during billing. Your edits were protected; contact support for a credit adjustment.`);
      return;
    }
    await this.app.vault.modify(file, correctedText);
    new import_obsidian6.Notice(`Culebra corrected ${file.name}.`);
  }
  /** Ask the configured provider for corrected text without mutating the vault. */
  async correctText(originalText, targetLabel) {
    if (!originalText.trim()) return null;
    const queued = await this.aiQueue.enqueue(`Correction for ${targetLabel}`, originalText, async () => {
      try {
        return await managedText(gatewayFor(this.settings), originalText, "correct", { input_characters: codePoints(originalText) });
      } catch (error) {
        new import_obsidian6.Notice(error instanceof Error ? error.message : "Preview unavailable.");
        return null;
      }
    });
    return queued.status === "completed" ? queued.value : null;
  }
};
var CorrectionReviewModal = class extends import_obsidian6.Modal {
  constructor(app, target, before, after) {
    super(app);
    this.target = target;
    this.before = before;
    this.after = after;
    this.settled = false;
  }
  waitForResult() {
    this.open();
    return new Promise((resolve) => {
      this.resolveResult = resolve;
    });
  }
  onOpen() {
    this.contentEl.createEl("h2", { text: `Review correction: ${this.target}` });
    const diff = this.contentEl.createEl("pre", { text: `BEFORE
${this.before}

AFTER
${this.after}` });
    diff.style.whiteSpace = "pre-wrap";
    diff.style.maxHeight = "55vh";
    diff.style.overflow = "auto";
    const actions = this.contentEl.createDiv();
    actions.createEl("button", { text: "Cancel" }).onclick = () => this.finish(false);
    actions.createEl("button", { text: "Apply correction", cls: "mod-cta" }).onclick = () => this.finish(true);
  }
  finish(approved) {
    if (this.settled) return;
    this.settled = true;
    this.resolveResult(approved);
    this.close();
  }
  onClose() {
    if (!this.settled) {
      this.settled = true;
      this.resolveResult(false);
    }
    this.contentEl.empty();
  }
};
var CulebraSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.creditsSummaryEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Culebra AI Spell Correct" });
    new import_obsidian6.Setting(containerEl).setName("Settings mode").setDesc("Simple shows everyday controls. Advanced adds customization and troubleshooting.").addDropdown((dropdown) => dropdown.addOption("simple", "Simple").addOption("advanced", "Advanced").setValue(this.plugin.settings.settingsMode).onChange(async (value) => {
      this.plugin.settings.settingsMode = value === "advanced" ? "advanced" : "simple";
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "Getting started" });
    containerEl.createEl("p", {
      text: "Select text in a note, or leave the selection empty to correct the current note. Then choose Culebra from the editor menu, command palette, or a Markdown file's context menu. Culebra applies the correction immediately and supports Undo."
    });
    new import_obsidian6.Setting(containerEl).setName("Review before applying").setDesc("Off by default for one-click corrections. Turn on to see a before/after review for each correction.").addToggle((toggle) => toggle.setValue(this.plugin.settings.reviewBeforeApply).onChange(async (value) => {
      this.plugin.settings.reviewBeforeApply = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("p", {
      text: "Correction requests send only the text you explicitly choose to OpenRouter. Use Undo if a correction is not wanted."
    });
    if (this.plugin.settings.settingsMode === "advanced") {
      new import_obsidian6.Setting(containerEl).setName("Managed model").setDesc("Constance selects the authorized economical model and output limits.");
      new import_obsidian6.Setting(containerEl).setName("AI request queue").setDesc("Inspect progress or remove waiting corrections; the active request continues.").addButton((button) => button.setButtonText("Show queue").onClick(() => this.plugin.aiQueue.open()));
      this.plugin.support.addDiagnosticsSetting(containerEl);
    }
    containerEl.createEl("h3", { text: "Credits & billing" });
    containerEl.createEl("p", {
      text: "Corrections are metered by input characters. Each billing account gets a one-time 2,000-character starter allowance across linked installations; buy more below when you run out."
    });
    this.creditsSummaryEl = containerEl.createEl("p", { cls: "culebra-credits-summary" });
    this.renderCreditsSummary();
    addBillingAccountSettings(containerEl, { state: this.plugin.settings, appId: CONSTANCE_APP_ID, installationId: this.plugin.settings.constanceDeviceId, appVersion: this.plugin.manifest.version, persist: () => this.plugin.saveSettings(), syncBalance: () => syncPurchasedCreditsFromConstance(this.plugin), refresh: () => this.display() });
    addLivePacks(containerEl, gatewayFor(this.plugin.settings));
    new import_obsidian6.Setting(containerEl).setName("Refresh balance").setDesc("Pull the latest purchased-credit balance from Constance.").addButton(
      (button) => button.setButtonText("Refresh balance").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Refreshing...");
        try {
          await syncPurchasedCreditsFromConstance(this.plugin, true);
          this.renderCreditsSummary();
        } catch (e) {
          new import_obsidian6.Notice("Could not refresh balance. Please try again.");
        } finally {
          button.setDisabled(false);
          button.setButtonText("Refresh balance");
        }
      })
    );
    void syncPurchasedCreditsFromConstance(this.plugin).then(() => this.renderCreditsSummary()).catch(() => {
    });
  }
  renderCreditsSummary() {
    if (!this.creditsSummaryEl) {
      return;
    }
    const { freeCredits, purchasedCredits } = this.plugin.settings;
    const totalChars = freeCredits + purchasedCredits;
    this.creditsSummaryEl.setText(
      `Characters remaining: ${totalChars.toLocaleString()} (${freeCredits.toLocaleString()} free + ${purchasedCredits.toLocaleString()} purchased)`
    );
  }
};
