/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// publish/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CulebraSpellCorrectPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var OPENROUTER_CHAT_COMPLETIONS_URL = "https://openrouter.ai/api/v1/chat/completions";
var DEFAULT_MODEL = "~deepseek/deepseek-v4-flash-latest";
var REMOTE_MANIFEST_PASSPHRASE = "Kivu.RemoteKeyManifest.v1.2026D";
var REMOTE_MANIFEST_URL = "https://raw.githubusercontent.com/tutivsoft-com/Resources/main/tool-app-Culebra-Obsidian-AI-Auto-Correct-Spelling.txt";
function base64ToBytes(b64) {
  const binary = atob(b64);
  const bytes = new Uint8Array(new ArrayBuffer(binary.length));
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}
async function decryptSecretEnvelope(envelope, passphrase) {
  if (envelope.x !== "AES-256-GCM" || envelope.w !== "PBKDF2-HMAC-SHA256") {
    throw new Error(`Unsupported manifest envelope algorithm/kdf: ${envelope.x} / ${envelope.w}`);
  }
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(passphrase),
    { name: "PBKDF2" },
    false,
    ["deriveKey"]
  );
  const key = await window.crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt: base64ToBytes(envelope.a),
      iterations: envelope.n,
      hash: "SHA-256"
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false,
    ["decrypt"]
  );
  const ciphertext = base64ToBytes(envelope.c);
  const tag = base64ToBytes(envelope.d);
  const ciphertextAndTag = new Uint8Array(new ArrayBuffer(ciphertext.length + tag.length));
  ciphertextAndTag.set(ciphertext, 0);
  ciphertextAndTag.set(tag, ciphertext.length);
  const plaintext = await window.crypto.subtle.decrypt(
    { name: "AES-GCM", iv: base64ToBytes(envelope.b) },
    key,
    ciphertextAndTag
  );
  return new TextDecoder().decode(plaintext);
}
function selectSlot(manifest, wantState) {
  var _a;
  const byMarker = manifest.r.find((slot) => slot.ii === wantState);
  if (byMarker) {
    return byMarker;
  }
  const fallbackState = wantState === "active" ? "0" : "1";
  return (_a = manifest.r.find((slot) => slot.s === fallbackState)) != null ? _a : null;
}
async function fetchRemoteManifest(url) {
  const response = await (0, import_obsidian.requestUrl)({ url, method: "GET", throw: false });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Manifest fetch failed: HTTP ${response.status}`);
  }
  return response.json;
}
async function tryDecryptManifestKey(manifest, source) {
  const active = selectSlot(manifest, "active");
  if (active) {
    try {
      const key = (await decryptSecretEnvelope(active.v, REMOTE_MANIFEST_PASSPHRASE)).trim();
      if (key) return key;
    } catch (error) {
      console.warn("Culebra: active manifest slot failed to decrypt", source, error);
    }
  }
  const next = selectSlot(manifest, "next");
  if (next) {
    try {
      const key = (await decryptSecretEnvelope(next.v, REMOTE_MANIFEST_PASSPHRASE)).trim();
      if (key) return key;
    } catch (error) {
      console.warn("Culebra: next manifest slot failed to decrypt", source, error);
    }
  }
  throw new Error("Remote key manifest did not decrypt to a usable key.");
}
async function fetchRemoteApiKey() {
  try {
    const manifest = await fetchRemoteManifest(REMOTE_MANIFEST_URL);
    return await tryDecryptManifestKey(manifest, REMOTE_MANIFEST_URL);
  } catch (primaryError) {
    console.warn("Culebra: primary manifest failed, trying next-manifest fallback", primaryError);
    const primaryManifest = await fetchRemoteManifest(REMOTE_MANIFEST_URL).catch(() => null);
    const nextUrl = primaryManifest == null ? void 0 : primaryManifest.n;
    if (nextUrl && nextUrl !== REMOTE_MANIFEST_URL) {
      const nextManifest = await fetchRemoteManifest(nextUrl);
      return await tryDecryptManifestKey(nextManifest, nextUrl);
    }
    throw primaryError;
  }
}
var SPELL_CORRECT_INSTRUCTIONS = `You are Culebra AI Spell Correct, a careful copy editor for an Obsidian Markdown vault.

Task:
Correct only spelling, grammar, punctuation, capitalization, repeated spaces, and obvious typing mistakes.

Hard rules:
- Preserve the user's meaning, intent, factual claims, opinions, tone, and emotional force.
- Do not censor, sanitize, moralize, soften, rewrite, summarize, add warnings, or alter controversial/offensive/sensitive wording.
- The user is in India. Preserve Indian names, place names, organization names, common Indian English wording, Hinglish-style proper nouns, and culturally specific terms unless they are clearly misspelled.
- When an Indian personal name, city, state, company, or other proper noun is clearly present with wrong casing, correct the capitalization, for example rahul to Rahul and bengaluru to Bengaluru.
- Preserve Markdown structure, headings, bullets, numbered lists, tables, links, tags, code blocks, inline code, YAML frontmatter, Obsidian wiki links, embeds, and callouts.
- Preserve normal paragraph breaks.
- If there are more than one blank line between paragraphs, collapse them to one blank line.
- Clean repeated spaces where safe, but do not damage code, tables, URLs, or intentional Markdown spacing.
- Return only the corrected text. Do not wrap it in code fences. Do not add commentary.`;
var CONSTANCE_BASE_URL = "https://app.tutivsoft.com";
var CONSTANCE_APP_ID = "culebra-ai-spell-correct";
var CONSTANCE_PRICE_IDS = {
  usd_001: "pri_01m0b7grv1cmt42gqfpc0v835k",
  // $1  -> 20,000 characters
  usd_005: "pri_01m0b7gsghrh315zvfxnxx4w38",
  // $5  -> 160,000 characters
  usd_015: "pri_01m0b7gt2jyj6s2a6dpkdvfdsr"
  // $15 -> 640,000 characters
};
function generateSecureDeviceId() {
  const bytes = new Uint8Array(16);
  window.crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
function generateEventId() {
  const bytes = new Uint8Array(12);
  window.crypto.getRandomValues(bytes);
  return "evt_" + Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
async function fetchConstanceEntitlements(deviceId) {
  var _a;
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_BASE_URL}/api/v1/public/browser/entitlements`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      app_id: CONSTANCE_APP_ID,
      external_customer_id: deviceId,
      machine_id: deviceId
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Entitlement sync failed: HTTP ${response.status}`);
  }
  return (_a = response.json) == null ? void 0 : _a.data;
}
async function spendConstanceCredits(deviceId, amount) {
  var _a, _b, _c;
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_BASE_URL}/api/v1/public/browser/credits/spend`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        app_id: CONSTANCE_APP_ID,
        external_customer_id: deviceId,
        machine_id: deviceId,
        amount,
        event_id: generateEventId()
      }),
      throw: false
    });
    if (response.status === 402 || response.status === 404) {
      return { kind: "insufficient" };
    }
    if (response.status < 200 || response.status >= 300) {
      return { kind: "error" };
    }
    const balance = (_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance;
    return { kind: "ok", balance: Math.max(0, Number(balance) || 0) };
  } catch (error) {
    console.error("Culebra: Constance credit spend call failed", error);
    return { kind: "error" };
  }
}
async function syncPurchasedCreditsFromConstance(plugin) {
  var _a;
  if (!plugin.settings.constanceDeviceId) {
    return;
  }
  try {
    const entitlement = await fetchConstanceEntitlements(plugin.settings.constanceDeviceId);
    const serverBalance = (_a = entitlement == null ? void 0 : entitlement.credits) == null ? void 0 : _a.balance;
    plugin.settings.purchasedCredits = Math.max(0, Number(serverBalance) || 0);
    await plugin.saveSettings();
  } catch (error) {
    console.error("Culebra: Constance entitlement sync failed", error);
  }
}
var DEFAULT_SETTINGS = {
  model: DEFAULT_MODEL,
  apiKey: "",
  constanceDeviceId: "",
  billingEmail: "",
  freeCredits: 2e3,
  purchasedCredits: 0,
  onboardingSeen: false
};
var CulebraSpellCorrectPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    // Cached once resolved so every correction doesn't re-fetch the manifest;
    // cleared and retried on failure in case the key was rotated mid-session.
    this.remoteApiKeyCache = null;
  }
  async resolveApiKey() {
    const manualKey = this.settings.apiKey.trim();
    if (manualKey) {
      return manualKey;
    }
    if (this.remoteApiKeyCache) {
      return this.remoteApiKeyCache;
    }
    const key = await fetchRemoteApiKey();
    this.remoteApiKeyCache = key;
    return key;
  }
  async onload() {
    await this.loadSettings();
    if (!this.settings.constanceDeviceId) {
      this.settings.constanceDeviceId = generateSecureDeviceId();
      await this.saveSettings();
    }
    if (!this.settings.onboardingSeen) {
      this.settings.onboardingSeen = true;
      await this.saveSettings();
      new import_obsidian.Notice("Culebra is ready. Select text or open a note, then choose Culebra to begin.");
    }
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const hasSelection = editor.getSelection().trim().length > 0;
        menu.addItem((item) => {
          item.setTitle(hasSelection ? "Culebra: Correct selected text" : "Culebra: Correct current note").setIcon("spell-check").onClick(() => {
            void this.correctEditorText(editor);
          });
        });
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") {
          return;
        }
        menu.addItem((item) => {
          item.setTitle("Culebra: Correct this Markdown file").setIcon("spell-check").onClick(() => {
            void this.correctFile(file);
          });
        });
      })
    );
    this.addCommand({
      id: "spell-correct",
      name: "Culebra: Correct selection or current note",
      editorCallback: (editor) => {
        void this.correctEditorText(editor);
      }
    });
    this.addSettingTab(new CulebraSettingTab(this.app, this));
    new import_obsidian.Notice("Culebra AI Spell Correct loaded");
    void syncPurchasedCreditsFromConstance(this);
  }
  async loadSettings() {
    const savedSettings = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedSettings);
    if (savedSettings && typeof savedSettings.onboardingSeen !== "boolean") {
      this.settings.onboardingSeen = true;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openBuyCheckout(tier) {
    const email = this.settings.billingEmail.trim();
    if (!email) {
      new import_obsidian.Notice("Enter a billing email in Culebra settings before buying credits.");
      return;
    }
    const priceId = CONSTANCE_PRICE_IDS[tier];
    if (!priceId || priceId === "PENDING_PROVISIONING") {
      new import_obsidian.Notice("Culebra billing is not available yet because Paddle prices are still being provisioned.");
      return;
    }
    const params = new URLSearchParams({
      app_id: CONSTANCE_APP_ID,
      price_id: priceId,
      email,
      external_customer_id: this.settings.constanceDeviceId
    });
    window.open(`${CONSTANCE_BASE_URL}/buy?${params.toString()}`, "_blank");
    this.pollAfterCheckout();
  }
  pollAfterCheckout() {
    let attempts = 0;
    const intervalId = window.setInterval(() => {
      attempts += 1;
      void syncPurchasedCreditsFromConstance(this);
      if (attempts >= 6) {
        window.clearInterval(intervalId);
      }
    }, 15e3);
  }
  /**
   * Reserves the character-based cost only after the user approves a preview.
   * The local free-character pool is used first, followed by the Constance
   * balance; transient balance failures fail open so an approved edit is not
   * silently discarded.
   */
  async chargeOneCredit(textLength) {
    const cost = Math.max(1, Math.ceil(textLength / 1e3));
    if (this.settings.freeCredits >= cost) {
      this.settings.freeCredits -= cost;
      await this.saveSettings();
      return true;
    }
    const result = await spendConstanceCredits(this.settings.constanceDeviceId, cost);
    if (result.kind === "ok") {
      this.settings.purchasedCredits = result.balance;
      await this.saveSettings();
      return true;
    }
    if (result.kind === "insufficient") {
      this.settings.purchasedCredits = 0;
      await this.saveSettings();
      new import_obsidian.Notice("Culebra: out of characters. Buy more in plugin settings (Buy $1 / $5 / $15).");
      return false;
    }
    console.warn("Culebra: credit spend check failed; proceeding and will reconcile on next sync.");
    return true;
  }
  /** Correct the current selection, or the whole active note when no text is selected. */
  async correctEditorText(editor) {
    const selection = editor.getSelection();
    const hasSelection = selection.trim().length > 0;
    const originalText = hasSelection ? selection : editor.getValue();
    const target = hasSelection ? "selection" : "current note";
    const correctedText = await this.correctText(originalText, target);
    if (!correctedText) {
      return;
    }
    if (correctedText === originalText) {
      new import_obsidian.Notice(`Culebra found no changes in the ${target}.`);
      return;
    }
    const shouldApply = await new CorrectionPreviewModal(
      this.app,
      target,
      originalText,
      correctedText
    ).waitForDecision();
    if (!shouldApply || !await this.chargeOneCredit(originalText.length)) {
      return;
    }
    if (hasSelection) {
      editor.replaceSelection(correctedText);
    } else {
      editor.setValue(correctedText);
    }
    new import_obsidian.Notice(`Culebra corrected ${target}. Undo with Ctrl/Cmd+Z if needed.`);
  }
  /** Preview and, after approval, replace the contents of one Markdown file. */
  async correctFile(file) {
    const originalText = await this.app.vault.read(file);
    const correctedText = await this.correctText(originalText, file.name);
    if (!correctedText) {
      return;
    }
    if (correctedText === originalText) {
      new import_obsidian.Notice(`Culebra found no changes in ${file.name}.`);
      return;
    }
    const shouldApply = await new CorrectionPreviewModal(
      this.app,
      file.name,
      originalText,
      correctedText
    ).waitForDecision();
    if (!shouldApply || !await this.chargeOneCredit(originalText.length)) {
      return;
    }
    await this.app.vault.modify(file, correctedText);
    new import_obsidian.Notice(`Culebra corrected ${file.name}.`);
  }
  /** Ask the configured provider for corrected text without mutating the vault. */
  async correctText(originalText, targetLabel) {
    if (!originalText.trim()) {
      new import_obsidian.Notice("Culebra found no text to correct.");
      return null;
    }
    let apiKey;
    try {
      apiKey = await this.resolveApiKey();
    } catch (error) {
      console.error("Culebra: failed to resolve an OpenRouter API key", error);
      new import_obsidian.Notice("Culebra could not fetch its built-in API key. Check your connection, or add your own OpenRouter key in settings.");
      return null;
    }
    new import_obsidian.Notice(`Culebra is correcting ${targetLabel}...`);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: OPENROUTER_CHAT_COMPLETIONS_URL,
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: this.settings.model.trim() || DEFAULT_MODEL,
          messages: [
            { role: "system", content: SPELL_CORRECT_INSTRUCTIONS },
            { role: "user", content: originalText }
          ]
        }),
        throw: false
      });
      if (response.status < 200 || response.status >= 300) {
        console.error("Culebra AI Spell Correct failed", response.status, response.text);
        new import_obsidian.Notice("Culebra correction failed. Check the developer console.");
        return null;
      }
      const correctedText = extractResponseText(response.json);
      if (!correctedText.trim()) {
        new import_obsidian.Notice("Culebra received an empty response; no changes made.");
        return null;
      }
      return correctedText;
    } catch (error) {
      console.error("Culebra AI Spell Correct failed", error);
      new import_obsidian.Notice("Culebra correction failed. Check the developer console.");
      return null;
    }
  }
};
function extractResponseText(responseJson) {
  var _a, _b, _c;
  if (!responseJson || typeof responseJson !== "object") {
    return "";
  }
  const response = responseJson;
  const content = (_c = (_b = (_a = response.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  return typeof content === "string" ? content : "";
}
var CulebraSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.creditsSummaryEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Culebra AI Spell Correct" });
    containerEl.createEl("h3", { text: "Getting started" });
    containerEl.createEl("p", {
      text: "Select text in a note, or leave the selection empty to correct the current note. Then choose Culebra from the editor menu, command palette, or a Markdown file's context menu. Culebra shows a before-and-after preview before applying anything."
    });
    containerEl.createEl("p", {
      text: "Correction requests send only the text you explicitly choose to OpenRouter. Review the preview carefully before applying it."
    });
    new import_obsidian.Setting(containerEl).setName("Model").setDesc(`OpenRouter model id. Default: ${DEFAULT_MODEL}`).addText(
      (text) => text.setPlaceholder(DEFAULT_MODEL).setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value.trim() || DEFAULT_MODEL;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("OpenRouter API key (optional)").setDesc("Culebra fetches its own built-in key automatically. Only set this to override it with your own OpenRouter key.").addText(
      (text) => text.setPlaceholder("sk-or-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    const apiKeyInput = containerEl.querySelector("input[placeholder='sk-or-...']");
    if (apiKeyInput) {
      apiKeyInput.type = "password";
    }
    containerEl.createEl("h3", { text: "Credits & billing" });
    containerEl.createEl("p", {
      text: "Each correction costs 1 credit per 1,000 characters. New installs start with 2,000 free characters; buy more below when you run out."
    });
    this.creditsSummaryEl = containerEl.createEl("p", { cls: "culebra-credits-summary" });
    this.renderCreditsSummary();
    new import_obsidian.Setting(containerEl).setName("Billing email").setDesc("Used for your Paddle purchase receipt. Not required to check your balance -- that uses this device's id.").addText(
      (text) => text.setPlaceholder("you@example.com").setValue(this.plugin.settings.billingEmail).onChange(async (value) => {
        this.plugin.settings.billingEmail = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Buy credits").setDesc("Opens TutivSoft billing (Constance) in your browser to complete payment via Paddle.").addButton(
      (button) => button.setButtonText("Buy $1 (20,000 characters)").onClick(() => {
        this.plugin.openBuyCheckout("usd_001");
      })
    ).addButton(
      (button) => button.setButtonText("Buy $5 (160,000 characters)").onClick(() => {
        this.plugin.openBuyCheckout("usd_005");
      })
    ).addButton(
      (button) => button.setButtonText("Buy $15 (640,000 characters)").onClick(() => {
        this.plugin.openBuyCheckout("usd_015");
      })
    );
    new import_obsidian.Setting(containerEl).setName("Refresh balance").setDesc("Pull the latest purchased-credit balance from Constance.").addButton(
      (button) => button.setButtonText("Refresh balance").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Refreshing...");
        await syncPurchasedCreditsFromConstance(this.plugin);
        this.renderCreditsSummary();
        button.setDisabled(false);
        button.setButtonText("Refresh balance");
      })
    );
    void syncPurchasedCreditsFromConstance(this.plugin).then(() => this.renderCreditsSummary());
  }
  renderCreditsSummary() {
    if (!this.creditsSummaryEl) {
      return;
    }
    const { freeCredits, purchasedCredits } = this.plugin.settings;
    const totalChars = freeCredits + purchasedCredits;
    this.creditsSummaryEl.setText(
      `Characters remaining: ${totalChars.toLocaleString()} (${freeCredits.toLocaleString()} free + ${purchasedCredits.toLocaleString()} purchased)`
    );
  }
};
var CorrectionPreviewModal = class extends import_obsidian.Modal {
  constructor(app, targetLabel, originalText, correctedText) {
    super(app);
    this.targetLabel = targetLabel;
    this.originalText = originalText;
    this.correctedText = correctedText;
    this.settled = false;
    this.decision = new Promise((resolve) => {
      this.resolveDecision = resolve;
    });
  }
  waitForDecision() {
    this.open();
    return this.decision;
  }
  onOpen() {
    this.setTitle(`Review correction: ${this.targetLabel}`);
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("p", {
      text: "Review the proposed changes. Nothing will be changed until you apply the correction."
    });
    const previewGrid = contentEl.createDiv({ cls: "culebra-preview-grid" });
    const before = previewGrid.createDiv({ cls: "culebra-preview-pane" });
    before.createEl("h3", { text: "Before" });
    before.createEl("pre", { cls: "culebra-preview-text", text: this.originalText });
    const after = previewGrid.createDiv({ cls: "culebra-preview-pane" });
    after.createEl("h3", { text: "After" });
    after.createEl("pre", { cls: "culebra-preview-text", text: this.correctedText });
    const buttons = contentEl.createDiv({ cls: "modal-button-container" });
    const cancelButton = buttons.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => this.finish(false));
    const applyButton = buttons.createEl("button", { text: "Apply correction" });
    applyButton.classList.add("mod-cta");
    applyButton.addEventListener("click", () => this.finish(true));
  }
  onClose() {
    this.finish(false);
  }
  finish(accepted) {
    if (this.settled) {
      return;
    }
    this.settled = true;
    this.resolveDecision(accepted);
    this.close();
  }
};
